[project]
name = "HiFiNet"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Nguyen Tri Nghia", email = "nghiant@mailbox.org"},
]
dependencies = [
	"hydra_zen",
	"pandas",
	"numpy",
	"typer",
	"loguru"
]
requires-python = "==3.12.*"
readme = "README.md"
license = "MIT"


[tool.pdm]
distribution = true

[tool.pdm.build]
include = "hifinet/"

[project.scripts]
hifinet = "src.cli:app"
